# KubeArmor is an open source software that enables you to protect your cloud workload at run-time.
# To learn more about KubeArmor visit: 
# https://www.accuknox.com/kubearmor/ 


apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-wordpress-wp-config-block
  namespace: app
spec:
  message: "(Alert) someone tried to open wp-config file"
  tags: ["Wordpress"]
  selector:
    matchLabels:
      app: MyWordpress |
  file:
    severity: 9
    matchPaths:
    - path: /var/www/html/wp-config.php
      fromSource:
      - path: /bin/cat
